version: '3.5'
services:

  etl-proof-of-concept-node:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /src
    volumes:
      - ./app/:/src
    environment:
      - MYSQL_DATABASE=newschema
      - MYSQL_HOST=etl-proof-of-concept-database-server
      - MYSQL_PORT=33061
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Up6KjbnEV4Hgfo75YM393QdQsK3Z0aTNBz0DoirrW+c
      - INFURA_API_KEY=9ba2ced9fa6345ddb1b20992630b885d
    ports:
      - 3001:3001
    container_name: "etl-proof-of-concept-node"

    networks:
      - rippled-network

networks:
  rippled-network:
    name: rippled-network
